{
 "title": "AWS Infrastructure",
 "description": "Visualize estimated AWS charges per AWS resource (EC2, S3, ...)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": "*" },
   { "name": "host", "label": "Host", "query": "$group.*" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "CloudWatch" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Alarms - ALARM" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Running Instances Ondemand" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Services usage on AWS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "ELB Application" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "ELB Classic" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Running Instances" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "EC2" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Volumes EBS" ],
       "text": "setAlias(Volumes EBS)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Volumes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Lambda" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Lambda" ],
       "text": "setAlias(Lambda)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Funçoes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "S3" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Buckets S3" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$group" },
     "item": { "filter": "Cluster RDS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SNS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Topics SNS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Fila SQS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "ElastiCache" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Cluster Redis" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Quantidade Elastic IP" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "targets": [
    {
     "application": { "filter": "Billing" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Billing Account" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "BILLING",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Billing" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Billing Total" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "aggregation": "Last",
     "application": { "filter": "Billing" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Billing Account" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Running Instances EC2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "EC2" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Running Instances" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "application": { "filter": "EC2" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Running Instances Ondemand" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "application": { "filter": "EC2" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Running Instances Spot" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 4 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Stopped instances" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 4 },
   "targets": [
    {
     "application": { "filter": "Billing" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Billing Total" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "content": "\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "targets": [
    {
     "application": { "filter": "S3" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Buckets S3" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Network Interfaces In-Use" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
   "targets": [
    {
     "application": { "filter": "Lambda" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Funçoes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Volumes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 9 },
   "targets": [
    {
     "application": { "filter": "Backup" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Backup Plans" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "ELB Application" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 9 },
   "targets": [
    {
     "application": { "filter": "ECS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Cluster ECS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 9 },
   "targets": [
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Cluster RDS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "targets": [
    {
     "application": { "filter": "ElastiCache" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Nó Redis" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 9 },
   "targets": [
    {
     "application": { "filter": "SQS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Fila SQS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Quantidade Elastic IP" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "AMIs" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "targets": [
    {
     "application": { "filter": "S3" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Quantidade Buckets S3 Sem Criptografia"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 11 },
   "targets": [
    {
     "application": { "filter": "Lambda" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Qtd. Lambdas sem invocation nos ultimos 90 dias"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 11 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Volumes Available" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 11 },
   "targets": [
    {
     "application": { "filter": "Backup" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Backup Suceed" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Network Interfaces Available" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "targets": [
    {
     "application": { "filter": "IAM" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Quantidade Users" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 12 },
   "targets": [
    {
     "application": { "filter": "ECS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Task Definitions" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 12 },
   "targets": [
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Instances RDS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 12 },
   "targets": [
    {
     "application": { "filter": "ElastiCache" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Cluster Redis" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 12 },
   "targets": [
    {
     "application": { "filter": "SNS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Topics SNS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Quantidade Elastic IP Sem Uso" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Snapshots" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "targets": [
    {
     "application": { "filter": "S3" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Quantidade Buckets S3 Publicos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
   "targets": [
    {
     "application": { "filter": "Lambda" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Qtd. Lambdas sem invocation nos ultimos 180 dias"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Volumes nao Encriptados" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 13 },
   "targets": [
    {
     "application": { "filter": "Backup" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Backup Failed" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Itens sem TAG \"Name\" ou \"Terraform\"",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "content": "\n\n\n\n"
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Instancias Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Buckets S3 Sem Tag" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 16 },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Lambas Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 16 },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "EBS Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 16 },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "ELB Application Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 16 },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "SQS Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 16 },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "SNS Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 16 },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "ElasticIP Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Deploys Executados no dia",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CodeDeploy" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Deploy Succeeded - HMG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CodeDeploy" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Deploy Failed - HMG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CodeDeploy" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Deploy Succeeded - TESTE" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CodeDeploy" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Deploy Failed - TESTE" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}